name: kelime_oyunu_ai
description: Kelime Oyunu AI Studio App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: ^3.18.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#0a0a20"
  # image: assets/splash_logo.png # Opsiyonel: Eğer logo varsa burayı açın

flutter:
  uses-material-design: true
  assets:
    - assets/www/
    - assets/www/assets/
    # END ASSETS
