import { Question } from "./types";

export const QUESTIONS_POOL: Question[] = [
  // 4 Harfli
  { word: "KASA", definition: "Değerli eşyaları saklamaya yarayan, genellikle çelikten yapılmış dolap.", length: 4 },
  { word: "ADET", definition: "Sayı, tane veya gelenek anlamlarına gelen kelime.", length: 4 },
  { word: "ASIR", definition: "Yüzyıl süren zaman dilimi.", length: 4 },
  { word: "BİNA", definition: "Yapı, konut veya iş yeri olarak kullanılan yer.", length: 4 },
  { word: "ÇARE", definition: "Bir sorunu çözmek için başvurulan yol, çözüm.", length: 4 },
  { word: "DERS", definition: "Öğrenilmesi gereken bilgi veya tecrübe.", length: 4 },
  { word: "EŞYA", definition: "Kullanılan nesnelerin genel adı.", length: 4 },
  { word: "FİRE", definition: "Bir malın ağırlığında veya miktarında meydana gelen eksilme.", length: 4 },
  { word: "GAYE", definition: "Ulaşılmak istenen sonuç, amaç.", length: 4 },
  { word: "HATA", definition: "Yanlışlık, kusur.", length: 4 },
  { word: "İLAÇ", definition: "Hastalıkları iyileştirmek için kullanılan madde.", length: 4 },
  { word: "JALE", definition: "Çiğ, şebnem anlamındaki isim.", length: 4 },
  { word: "KALE", definition: "Savunma amaçlı yapılan sağlam yapı.", length: 4 },
  { word: "LİSTE", definition: "Adların veya nesnelerin alt alta yazıldığı çizelge.", length: 4 },
  { word: "MAAŞ", definition: "Hizmet karşılığı ödenen aylık para.", length: 4 },
  { word: "NAAŞ", definition: "Ölen kimsenin vücudu, ceset.", length: 4 },
  { word: "OCAK", definition: "Yılın birinci ayı veya ateş yakılan yer.", length: 4 },
  { word: "PARE", definition: "Parça, lokma anlamındaki kelime.", length: 4 },
  { word: "RAZI", definition: "Kabul eden, boyun eğen.", length: 4 },
  { word: "SAAT", definition: "Zamanı ölçmeye yarayan araç.", length: 4 },
  { word: "ŞART", definition: "Bir şeyin olması için gereken durum, koşul.", length: 4 },
  { word: "TAHT", definition: "Hükümdarların oturduğu büyük koltuk.", length: 4 },
  { word: "UCUZ", definition: "Fiyatı düşük olan, pahalı karşıtı.", length: 4 },
  { word: "VAAZ", definition: "Dini konularda verilen öğüt.", length: 4 },
  { word: "YARA", definition: "Vücutta oluşan kesik veya zedelenme.", length: 4 },
  { word: "ZAMN", definition: "Süre, vakit anlamındaki kelime.", length: 4 },
  { word: "ARZU", definition: "İstek, dilek.", length: 4 },
  { word: "BATI", definition: "Güneşin battığı yön.", length: 4 },
  { word: "CİLT", definition: "Deri veya kitap kapağı.", length: 4 },
  { word: "DOĞU", definition: "Güneşin doğduğu yön.", length: 4 },
  { word: "ESER", definition: "Ortaya konulan yapıt.", length: 4 },
  { word: "FEZA", definition: "Uzay, gökyüzü boşluğu.", length: 4 },
  { word: "GIDA", definition: "Besin, yiyecek maddesi.", length: 4 },
  { word: "HARE", definition: "Parlak, dalgalı çizgi veya renk.", length: 4 },
  { word: "İSİM", definition: "Ad, bir kimseyi veya şeyi tanıtan kelime.", length: 4 },
  { word: "KATI", definition: "Sert, sıvı olmayan madde hali.", length: 4 },
  { word: "LAVA", definition: "Yanardağdan çıkan erimiş madde.", length: 4 },
  { word: "MODA", definition: "Toplumda geçici olarak yaygınlaşan beğeni.", length: 4 },
  { word: "NİNE", definition: "Büyükanne.", length: 4 },
  { word: "OKUL", definition: "Eğitim ve öğretim yapılan yer.", length: 4 },

  // 5 Harfli
  { word: "KALEM", definition: "Yazma, çizme vb. işlerde kullanılan araç.", length: 5 },
  { word: "DENİZ", definition: "Yeryüzünün büyük bir bölümünü kaplayan çok geniş ve tuzlu su kütlesi.", length: 5 },
  { word: "ABİDE", definition: "Anıt, önemli bir olayı hatırlatan yapı.", length: 5 },
  { word: "BAHAR", definition: "Kış ile yaz arasındaki mevsim.", length: 5 },
  { word: "CEVİZ", definition: "Sert kabuklu, içi yenen bir yemiş.", length: 5 },
  { word: "DÜNYA", definition: "Üzerinde yaşadığımız gezegen.", length: 5 },
  { word: "EVRAK", definition: "Yazılı belgeler, kağıtlar.", length: 5 },
  { word: "FİKİR", definition: "Düşünce, görüş.", length: 5 },
  { word: "GÜNEŞ", definition: "Dünyamızı aydınlatan ve ısıtan yıldız.", length: 5 },
  { word: "HAYAL", definition: "Zihinde canlandırılan görüntü.", length: 5 },
  { word: "İNSAN", definition: "Akıl ve konuşma yeteneği olan canlı.", length: 5 },
  { word: "KİTAP", definition: "Basılı veya yazılı kağıt yaprakların bütünü.", length: 5 },
  { word: "LİMAN", definition: "Gemilerin sığındığı, yük alıp boşalttığı yer.", length: 5 },
  { word: "MÜZİK", definition: "Seslerin uyumlu bir biçimde düzenlenmesi sanatı.", length: 5 },
  { word: "NAZAR", definition: "Bakış, göz değmesi.", length: 5 },
  { word: "ORMAN", definition: "Ağaçlarla kaplı geniş alan.", length: 5 },
  { word: "PAMUK", definition: "Yumuşak, beyaz bitkisel lif.", length: 5 },
  { word: "RADYO", definition: "Ses dalgalarını ileten cihaz.", length: 5 },
  { word: "SABAH", definition: "Günün başlangıç vakti.", length: 5 },
  { word: "ŞEHİR", definition: "Nüfusu yoğun, gelişmiş yerleşim yeri.", length: 5 },
  { word: "TARİH", definition: "Geçmişteki olayları inceleyen bilim.", length: 5 },
  { word: "UYGUR", definition: "Bir Türk boyu veya medeni anlamındaki kelime.", length: 5 },
  { word: "VATAN", definition: "Yurt, üzerinde yaşanılan toprak.", length: 5 },
  { word: "YALAN", definition: "Gerçeğe aykırı söz.", length: 5 },
  { word: "ZAMAN", definition: "Olayların geçtiği süre, vakit.", length: 5 },
  { word: "AKŞAM", definition: "Günün son saatleri.", length: 5 },
  { word: "BÖLGE", definition: "Sınırları belirlenmiş toprak parçası.", length: 5 },
  { word: "CÜMLE", definition: "Kelime dizisi, tümce.", length: 5 },
  { word: "DAİRE", definition: "Çemberin içindeki alan veya konut birimi.", length: 5 },
  { word: "ENERJİ", definition: "İş yapabilme yeteneği, güç.", length: 5 },
  { word: "FORMÜL", definition: "Bir kuralı simgelerle ifade etme.", length: 5 },
  { word: "GURUR", definition: "Övünç, özsaygı.", length: 5 },
  { word: "HUZUR", definition: "İç rahatlığı, dinginlik.", length: 5 },
  { word: "IŞIMA", definition: "Işık yayma, radyasyon.", length: 5 },
  { word: "İHALE", definition: "Bir işi en uygun teklifi verene verme.", length: 5 },
  { word: "KADRO", length: 5, definition: "Bir kuruluşta çalışanların bütünü." },
  { word: "LEVHA", length: 5, definition: "Tabela, düz ve geniş plaka." },
  { word: "MEKAN", length: 5, definition: "Yer, bulunulan alan." },
  { word: "NEHİR", length: 5, definition: "Akarsu, ırmak." },
  { word: "ORTAK", length: 5, definition: "Bir işe birlikte girenlerden her biri." },

  // 6 Harfli
  { word: "BARDAK", definition: "Su vb. içmek için kullanılan, genellikle camdan yapılan kap.", length: 6 },
  { word: "GÖZLÜK", definition: "Görme bozukluklarını düzeltmeye veya gözü korumaya yarayan araç.", length: 6 },
  { word: "ADALET", definition: "Hak ve hukuka uygunluk, doğruluk.", length: 6 },
  { word: "BAYRAK", definition: "Bir ulusu veya topluluğu simgeleyen kumaş.", length: 6 },
  { word: "CEVHER", definition: "Değerli taş veya bir şeyin özü.", length: 6 },
  { word: "DEPREM", definition: "Yer sarsıntısı, zelzele.", length: 6 },
  { word: "EKMEK", definition: "Un ve su ile yapılan temel gıda.", length: 6 },
  { word: "FIRTINA", definition: "Çok güçlü esen rüzgar.", length: 7 },
  { word: "GAZETE", definition: "Günlük haberleri veren basılı yayın.", length: 6 },
  { word: "HEYKEL", definition: "Taş, metal vb. maddelerden yapılan sanat eseri.", length: 6 },
  { word: "İSKELE", definition: "Gemilerin yanaştığı tahta veya beton yapı.", length: 6 },
  { word: "KAPTAN", definition: "Gemi veya uçak yöneten kimse.", length: 6 },
  { word: "LEZZET", definition: "Ağızda bırakılan tat.", length: 6 },
  { word: "MİMARİ", definition: "Yapı yapma sanatı.", length: 6 },
  { word: "NAMZET", definition: "Aday, bir işe talip olan.", length: 6 },
  { word: "OTOBÜS", definition: "Çok sayıda yolcu taşıyan araç.", length: 6 },
  { word: "PARLAK", definition: "Işık yansıtan, canlı.", length: 6 },
  { word: "REHBER", definition: "Yol gösteren kimse veya kitap.", length: 6 },
  { word: "SİGORTA", definition: "Güvence altına alma sistemi.", length: 7 },
  { word: "ŞEFFAF", definition: "Işığı geçiren, saydam.", length: 6 },
  { word: "TİYATRO", definition: "Sahnede oynanan oyun sanatı.", length: 7 },
  { word: "ULAŞIM", definition: "Bir yerden bir yere gitme işi.", length: 6 },
  { word: "VİCDAN", definition: "İyiyi kötüden ayıran iç duygu.", length: 6 },
  { word: "YARDIM", definition: "Destek olma, imdat.", length: 6 },
  { word: "ZEYTİN", definition: "Kahvaltıda yenen, yağı çıkarılan meyve.", length: 6 },
  { word: "ANLAYIŞ", definition: "Kavrayış, hoşgörü.", length: 7 },
  { word: "BİLGİN", definition: "Alim, çok bilgili kimse.", length: 6 },
  { word: "COŞKUN", definition: "Heyecanlı, taşkın.", length: 6 },
  { word: "DİNAMO", definition: "Hareket enerjisini elektriğe çeviren araç.", length: 6 },
  { word: "FELSEFE", definition: "Düşünce bilimi.", length: 7 },
  { word: "GURBET", definition: "Doğup büyüdüğü yerden uzak yer.", length: 6 },
  { word: "HAYRET", definition: "Şaşkınlık, şaşma.", length: 6 },
  { word: "IŞILTI", definition: "Hafif ve titrek ışık.", length: 6 },
  { word: "İBADET", definition: "Dini görevleri yerine getirme.", length: 6 },
  { word: "KAYNAK", length: 6, definition: "Bir şeyin çıktığı yer, menşe." },
  { word: "LİSANS", length: 6, definition: "Üniversite derecesi veya izin belgesi." },
  { word: "MESLEK", length: 6, definition: "Geçim sağlamak için yapılan iş." },
  { word: "NASİHAT", length: 6, definition: "Öğüt, yol gösterme." },
  { word: "ORANTI", length: 6, definition: "İki oran arasındaki eşitlik." },

  // 7 Harfli
  { word: "PENCERE", definition: "Yapılarda, ışık ve hava girmeye yarayan, çerçeveli açıklık.", length: 7 },
  { word: "ANAHTAR", definition: "Kilidi açıp kapamaya yarayan araç.", length: 7 },
  { word: "AKDENİZ", definition: "Türkiye'nin güneyindeki deniz.", length: 7 },
  { word: "BELEDİYE", definition: "Şehir işlerini yürüten kuruluş.", length: 7 },
  { word: "CESARET", definition: "Yüreklilik, korkusuzluk.", length: 7 },
  { word: "DİKKATLİ", definition: "Özen gösteren, titiz.", length: 7 },
  { word: "EĞLENCE", definition: "Keyifli vakit geçirme.", length: 7 },
  { word: "FABRİKA", definition: "Üretim yapılan büyük tesis.", length: 7 },
  { word: "GÖKYÜZÜ", definition: "Dünyayı saran hava tabakasının görünen kısmı.", length: 7 },
  { word: "HASTANE", definition: "Hastaların tedavi edildiği yer.", length: 7 },
  { word: "İLETİŞİM", definition: "Haberleşme, bilgi alışverişi.", length: 7 },
  { word: "KAVRAMA", definition: "Bir şeyi anlama, kavrama yeteneği.", length: 7 },
  { word: "LOKANTA", definition: "Yemek yenilen yer, restoran.", length: 7 },
  { word: "MAĞAZA", definition: "Büyük alışveriş yeri.", length: 7 },
  { word: "NASİHAT", definition: "Öğüt, birine verilen tavsiye.", length: 7 },
  { word: "OYUNCAK", definition: "Çocukların oynaması için yapılan nesne.", length: 7 },
  { word: "PIRLANTA", definition: "Değerli bir taş, elmasın işlenmiş hali.", length: 7 },
  { word: "RANDEVU", definition: "Buluşma zamanı ve yeri.", length: 7 },
  { word: "SİYASET", definition: "Politika, devlet yönetme sanatı.", length: 7 },
  { word: "ŞELALE", definition: "Yüksekten dökülen su, çağlayan.", length: 7 },
  { word: "TEHLİKE", definition: "Zarar görme ihtimali.", length: 7 },
  { word: "UYGARLIK", definition: "Medeniyet, gelişmişlik düzeyi.", length: 7 },
  { word: "VİTAMİN", definition: "Vücut için gerekli organik madde.", length: 7 },
  { word: "YETENEK", definition: "Beceri, kabiliyet.", length: 7 },
  { word: "ZİYARET", definition: "Birini görmeye gitme.", length: 7 },
  { word: "ANAYASA", definition: "Temel kanun, devletin temel yapısı.", length: 7 },
  { word: "BİSİKLET", definition: "İki tekerlekli, pedalsız araç.", length: 7 },
  { word: "COĞRAFİ", definition: "Yer şekilleriyle ilgili olan.", length: 7 },
  { word: "DENEYİM", definition: "Tecrübe, yaşanmışlık.", length: 7 },
  { word: "EKONOMİ", definition: "İktisat, üretim ve tüketim dengesi.", length: 7 },
  { word: "FESTİVAL", definition: "Sanat veya kültür şenliği.", length: 7 },
  { word: "GELENEK", definition: "Kuşaktan kuşağa aktarılan alışkanlık.", length: 7 },
  { word: "HAYVAN", definition: "Canlı varlıkların genel adı (insan hariç).", length: 7 },
  { word: "IŞINLANMA", definition: "Bir yerden bir yere anında gitme (hayali).", length: 9 },
  { word: "İMTİHAN", definition: "Sınav, deneme.", length: 7 },
  { word: "KALİTELİ", length: 7, definition: "Nitelikli, iyi yapılmış." },
  { word: "LOKOMOTİF", length: 9, definition: "Tren vagonlarını çeken araç." },
  { word: "MANTIKLI", length: 7, definition: "Akla uygun, tutarlı." },
  { word: "NEZAKET", length: 7, definition: "Kibarlık, naziklik." },
  { word: "OKYANUS", length: 7, definition: "Kıtaları ayıran büyük deniz." },

  // 8 Harfli
  { word: "AYAKKABI", definition: "Ayağa giyilen ve altı kösele, lastik vb. dayanıklı maddelerden yapılan giyecek.", length: 8 },
  { word: "MERDİVEN", definition: "Bir yere çıkmaya veya bir yerden inmeye yarayan basamaklar dizisi.", length: 8 },
  { word: "ARKADAŞ", definition: "Birbirine sevgi ve güven duyan kimselerden her biri.", length: 8 },
  { word: "BAŞARI", definition: "İstenilen sonuca ulaşma durumu.", length: 8 },
  { word: "COĞRAFYA", definition: "Yeryüzünü ve özelliklerini inceleyen bilim.", length: 8 },
  { word: "DENEYİM", definition: "Tecrübe, yaşantı yoluyla kazanılan bilgi.", length: 8 },
  { word: "EDEBİYAT", definition: "Yazın, söz sanatı.", length: 8 },
  { word: "FOTOĞRAF", definition: "Işıkla görüntü saptama sanatı.", length: 8 },
  { word: "GELENEK", definition: "Kuşaktan kuşağa aktarılan alışkanlıklar.", length: 8 },
  { word: "HAYVAN", definition: "Duygu ve hareket yeteneği olan canlı.", length: 8 },
  { word: "İSTATİSTİK", definition: "Verileri toplama ve yorumlama bilimi.", length: 10 },
  { word: "KÜTÜPHANE", definition: "Kitaplık, kitapların bulunduğu yer.", length: 9 },
  { word: "LOKOMOTİF", definition: "Tren vagonlarını çeken araç.", length: 9 },
  { word: "MANZARA", definition: "Bakıldığında görülen görünüş.", length: 8 },
  { word: "NASİHAT", definition: "Öğüt verme, tavsiyede bulunma.", length: 8 },
  { word: "OTOMOBİL", definition: "Dört tekerlekli motorlu taşıt.", length: 8 },
  { word: "PSİKOLOJİ", definition: "Ruh bilimi.", length: 9 },
  { word: "REKLAMCI", definition: "Tanıtım işiyle uğraşan kimse.", length: 8 },
  { word: "SÖZLÜKÇÜ", definition: "Sözlük hazırlayan uzman.", length: 8 },
  { word: "ŞAMPİYON", definition: "Birinci gelen, galip.", length: 8 },
  { word: "TEKNOLOJİ", definition: "Bilimsel bilginin pratik kullanımı.", length: 9 },
  { word: "UZMANLIK", definition: "Bir konuda derin bilgi sahibi olma.", length: 8 },
  { word: "VARLIKLI", definition: "Zengin, maddi durumu iyi olan.", length: 8 },
  { word: "YARATICI", definition: "Yeni bir şey ortaya koyan.", length: 8 },
  { word: "ZİYARETÇİ", definition: "Görmeye gelen kimse.", length: 8 },
  { word: "ANLATICI", definition: "Hikaye veya olay aktaran.", length: 8 },
  { word: "BEKLENTİ", definition: "Umulan şey, umut.", length: 8 },
  { word: "CÖMERTLİK", definition: "Eli açık olma durumu.", length: 9 },
  { word: "DÜRÜSTLÜK", definition: "Doğruluk, yalan söylememe.", length: 9 },
  { word: "ELEŞTİRİ", definition: "Bir şeyi iyi ve kötü yanlarıyla inceleme.", length: 8 },
  { word: "FARKINDALIK", definition: "Bilinçli olma durumu.", length: 10 },
  { word: "GÜVENLİK", definition: "Emniyet, tehlikeden uzak olma.", length: 8 },
  { word: "HAREKETLİ", definition: "Canlı, yerinde durmayan.", length: 9 },
  { word: "IŞIKLANDIRMA", definition: "Aydınlatma sistemi.", length: 12 },
  { word: "İLERLEME", definition: "Gelişme, daha iyiye gitme.", length: 8 },
  { word: "KAPASİTE", length: 8, definition: "Alabilme gücü, sığa." },
  { word: "LİTERATÜR", length: 9, definition: "Bir konudaki yazılı eserlerin bütünü." },
  { word: "MÜHENDİS", length: 8, definition: "Teknik işleri planlayan uzman." },
  { word: "NEZAKETLİ", length: 9, definition: "Kibar davranan kimse." },
  { word: "ÖĞRENCİLİK", length: 10, definition: "Öğrenci olma durumu." },

  // 9 Harfli
  { word: "BUZDOLABI", definition: "Yiyecek ve içecekleri soğuk tutarak bozulmalarını önleyen dolap.", length: 9 },
  { word: "KUMANDALI", definition: "Uzaktan yönetme düzeneği olan.", length: 9 },
  { word: "BİLGİSAYAR", definition: "Verileri işleyen elektronik cihaz.", length: 10 },
  { word: "ÇALIŞKAN", definition: "Çok çalışan, gayretli.", length: 9 },
  { word: "DÜRÜSTLÜK", definition: "Doğruluk, özü sözü bir olma.", length: 9 },
  { word: "EĞİTİMCİ", definition: "Eğitim işiyle uğraşan kimse.", length: 9 },
  { word: "FARKINDALIK", definition: "Bir şeyin farkında olma durumu.", length: 11 },
  { word: "GELECEK", definition: "Henüz yaşanmamış zaman, istikbal.", length: 9 },
  { word: "HAYIRSEVER", definition: "İyilik yapmayı seven kimse.", length: 10 },
  { word: "İMKANSIZ", definition: "Gerçekleşmesi mümkün olmayan.", length: 9 },
  { word: "KAHRAMAN", definition: "Yiğit, büyük işler başaran kimse.", length: 9 },
  { word: "LİBERALİZM", definition: "Özgürlükçü düşünce yapısı.", length: 10 },
  { word: "MATEMATİK", definition: "Sayı ve ölçü bilimi.", length: 9 },
  { word: "NEZAKETLİ", definition: "Kibar, nazik davranan.", length: 9 },
  { word: "ÖZGÜRLÜK", definition: "Hürriyet, kısıtlanmama durumu.", length: 9 },
  { word: "PLANLAYICI", definition: "İşleri önceden düzenleyen.", length: 10 },
  { word: "REKABETÇİ", definition: "Yarışmayı seven, hırslı.", length: 9 },
  { word: "SÜRDÜRÜLEBİLİR", definition: "Devam ettirilebilir olan.", length: 14 },
  { word: "ŞEFFAFLIK", definition: "Açıklık, gizli saklı olmama.", length: 9 },
  { word: "TASARIMCI", definition: "Dizayn yapan sanatçı veya uzman.", length: 9 },
  { word: "UYGULAMALI", definition: "Pratiğe dökülmüş olan.", length: 10 },
  { word: "VERİMLİLİK", definition: "Az kaynakla çok iş yapma.", length: 10 },
  { word: "YARATICILIK", definition: "Yeni fikirler üretme yeteneği.", length: 11 },
  { word: "ZENGİNLİK", definition: "Varlık, bol imkan.", length: 9 },
  { word: "ARAŞTIRMA", definition: "Bir konuyu derinlemesine inceleme.", length: 9 },
  { word: "BİREYSELLİK", definition: "Kişiye özel olma durumu.", length: 11 },
  { word: "CİDDİYETLİ", definition: "Ağırbaşlı, şaka yapmayan.", length: 10 },
  { word: "DENETLEYİCİ", definition: "Kontrol eden mekanizma.", length: 11 },
  { word: "ETKİLEYİCİ", definition: "İz bırakan, tesirli.", length: 10 },
  { word: "FELSEFECİ", definition: "Filozof, düşünür.", length: 9 },
  { word: "GÖSTERİŞLİ", definition: "Göz alıcı, şatafatlı.", length: 10 },
  { word: "HAYALPEREST", definition: "Düş kurmayı seven.", length: 10 },
  { word: "IŞIKLANDIRMA", definition: "Aydınlatma yapılmış olan.", length: 12 },
  { word: "İSTATİSTİK", definition: "Veri bilimiyle ilgili.", length: 10 },
  { word: "KÜRESELLEŞME", length: 12, definition: "Dünya çapında yayılma." },
  { word: "LİDERLİKLER", length: 12, definition: "Önderlik etme yetisi." },
  { word: "MODERNİZM", length: 9, definition: "Çağdaşlaşma akımı." },
  { word: "NESNELLİK", length: 9, definition: "Objektiflik, tarafsızlık." },
  { word: "ÖRGÜTLENME", length: 10, definition: "Teşkilatlanma süreci." },

  // 10 Harfli
  { word: "TELEVİZYON", definition: "Vericiden yayılan elektromanyetik dalgaları görüntü ve ses olarak veren cihaz.", length: 10 },
  { word: "DİKKATLİCE", definition: "Özenli bir biçimde, titizlikle.", length: 10 },
  { word: "CUMHURİYET", definition: "Halkın kendi kendini yönettiği rejim.", length: 10 },
  { word: "DEMOKRASİ", definition: "Halkın egemenliğine dayanan yönetim biçimi.", length: 10 },
  { word: "ELEKTRONİK", definition: "Elektrik akımıyla çalışan cihazlar bilimi.", length: 10 },
  { word: "FEDAKARLIK", definition: "Özveri, bir amaç için kendinden vazgeçme.", length: 10 },
  { word: "GÖREVLENDİRME", definition: "Birine iş verme, vazifelendirme.", length: 13 },
  { word: "HAYALPEREST", definition: "Sürekli hayal kuran kimse.", length: 10 },
  { word: "İSİMLENDİRME", definition: "Ad verme, adlandırma.", length: 12 },
  { word: "KİTAPSEVER", definition: "Kitap okumayı çok seven kimse.", length: 10 },
  { word: "LABORATUVAR", definition: "Bilimsel araştırmaların yapıldığı yer.", length: 11 },
  { word: "MİSAFİRPERVER", definition: "Konuksever, misafiri seven.", length: 13 },
  { word: "NAZİKLİKLE", definition: "Kibarca, nazik bir şekilde.", length: 10 },
  { word: "ÖĞRETMENLİK", definition: "Öğretme işi, muallimlik.", length: 11 },
  { word: "PLANLAMACI", definition: "Strateji kuran, düzenleyen.", length: 10 },
  { word: "REHBERLİKÇİ", definition: "Yol gösteren uzman.", length: 11 },
  { word: "SORUMLULUK", definition: "Mesuliyet, üstlenilen görev.", length: 10 },
  { word: "ŞEHİRCİLİK", definition: "Kent planlama bilimi.", length: 10 },
  { word: "TEKNOLOJİK", definition: "Teknik imkanlarla ilgili.", length: 10 },
  { word: "UYGULAYICI", definition: "Teoriyi pratiğe döken.", length: 10 },
  { word: "VATANSEVER", definition: "Yurdunu çok seven, yurtsever.", length: 10 },
  { word: "YARATICILIK", definition: "Kreatif olma durumu.", length: 11 },
  { word: "ZENGİNLEŞME", definition: "Varlık sahibi olma süreci.", length: 11 },
  { word: "ARAŞTIRMACI", definition: "İnceleme yapan uzman.", length: 11 },
  { word: "BİLGİSAYAR", definition: "Elektronik veri işleme cihazı.", length: 10 },
  { word: "CİDDİYETLE", definition: "Ağırbaşlı bir tavırla.", length: 10 },
  { word: "DENETLEYİCİ", definition: "Kontrol mekanizması.", length: 11 },
  { word: "ETKİLEYİCİ", definition: "Tesir bırakan, çarpıcı.", length: 10 },
  { word: "FARKINDALIK", definition: "Bilinçlenme, idrak etme.", length: 10 },
  { word: "GELENEKSEL", definition: "Ananelere uygun olan.", length: 10 },
  { word: "HAYIRSEVER", definition: "İyilik yapmayı seven.", length: 10 },
  { word: "IŞIKLANDIRMA", definition: "Aydınlatma işlemi.", length: 12 },
  { word: "İSTATİSTİK", definition: "Veri toplama ve analiz bilimi.", length: 10 },
  { word: "KÜRESELLEŞME", length: 12, definition: "Dünya ile bütünleşme." },
  { word: "LİDERLİKLE", length: 10, definition: "Önderlik vasfıyla." },
  { word: "MODERNLEŞME", length: 11, definition: "Çağdaşlaşma süreci." },
  { word: "NESNELLEŞME", length: 11, definition: "Objektifleşme durumu." },
  { word: "ÖRGÜTLENME", length: 10, definition: "Teşkilat kurma işi." },
  { word: "PSİKOLOJİK", length: 10, definition: "Ruhsal durumla ilgili." },
  { word: "REKABETÇİLİK", length: 12, definition: "Yarışmacı olma hali." }
];
